name = "cloud-mail-dev"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[dev]
ip = "0.0.0.0"

[[d1_databases]]
binding = "db"
database_name = "cloud_mail_d1"
database_id = "43b2763d-0f47-4c6e-ab92-6c4928ece2c7"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "cloud_mail_kv"
id = "36edbf617e1f4aa4afdeabcb682f69bb"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = "email"


[vars]
orm_log = false
domain = ["example.com", "example2.com", "example3.com", "example4.com"]
admin = "admin@example.com"
jwt_secret = "b7f29a1d-18e2-4d3b-941f-f6b2c97c02fd"
